paths:
  download: "/mnt/mp3/youtube/"
  relative: "youtube/"
  nfs_delay: 10

mqtt:
  host: arbiter.vm.nurd.space
  port: 1883

  topics:
    play: mpd/youtube-dl/play
    status: mpd/youtube-dl/status

mpd:
  host: localhost
  port: 6600

nurdbot:
  jsb-udp: /home/pi/mpdtube/jsb-udpsend
  python2: /usr/bin/python